import mongoose from "mongoose";
import { getuserid } from "@/src/Helper/usergetid";
const userdata = getuserid()

const ProfileregisterSchema = new mongoose.Schema({
  userid: { type: String, default: '' },
  profilephoto: { type: String, default: '' },
  galleryPhoto: {
    type: [String],
    default: []
  },
  assignedTo: { type: String, default: '' },
  name: { type: String, default: '' },
  gender: { type: String, default: '' },
  dateofBirth: { type: String, default: '' },
  religion: { type: String, default: '' },
  motherTongue: { type: String, default: '' },
  meritalStatus: { type: String, default: '' },
  caste: { type: String, default: '' },
  dosh: { type: String, default: '' },
  willingToMarry: { type: String, default: '' },
  countryLivingIn: { type: String, default: '' },
  stateLivingIn: { type: String, default: '' },
  cityLivingIn: { type: String, default: '' },
  height: { type: String, default: '' },
  physicalStatus: { type: String, default: '' },
  education: { type: String, default: '' },
  employedId: { type: String, default: '' },
  occupation: { type: String, default: '' },
  currency: { type: String, default: '' },
  annualIncome: { type: String, default: '' },
  familyStatus: { type: String, default: '' },
  familyType: { type: String, default: '' },
  familyValues: { type: String, default: '' },
  ancestralOrigin: { type: String, default: '' },
  message: { type: String, default: '' },
  agreeToPrivacyPolicy: { type: Boolean, default: true },
  bodyType: { type: String, default: '' },
  weight: { type: String, default: '' },
  drinkingHabits: { type: String, default: '' },
  eatingHabits: { type: String, default: '' },
  smokingHabits: { type: String, default: '' },
  knowToRead: { type: String, default: '' },
  fatherOccupation: { type: String },
  motherOccupation: { type: String },
  noOfBrother: { type: String },
  noOfBrotherMarried: { type: String },
  noOfSister: { type: String },
  noOfSisterMarried: { type: String },
  familyLocation: { type: String },
  ancestralOrigin: { type: String },
  citizenship: { type: String },
  college: { type: String },
  occupationInDetail: { type: String },
  Organization: { type: String },
  educationInDetails: { type: String },
  educationInDetails: { type: String },
  birthcity: { type: String },
  birthstate: { type: String },
  birthcountry: { type: String },
  birthhrs: { type: String },
  birthmins: { type: String },
  birthtime: { type: String },
  star: { type: String },
  rashi: { type: String },
  drinkinghabbit: { type: String },
  smokinghabits: { type: String },
  eatinghabbit: { type: String },
  ViewedByYou: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Profile' }],
  ViewedYou: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Profile' }],
  Shortlist: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Shortlist' }],
  date: { type: Date, default: Date.now },

});

export const registerschema = mongoose.models.profileregisters || mongoose.model("profileregisters", ProfileregisterSchema)
