export const hobbies = [
    "Acting",
    "Adventure sports",
    "Alternative healing / Medicine",
    "Art / Handicraft",
    "Astrology",
    "Baking",
    "Bike / Car enthusiast",
    "Bird watching",
    "Blogging / Video blogging",
    "Board games",
    "Book clubs",
    "Calligraphy",
    "Clubbing",
    "Collectibles",
    "Cooking",
    "Crosswords",
    "Dancing",
    "DIY (Do it yourself) projects",
    "Fashion design",
    "Film-making",
    "Fishing",
    "Gardening / Landscaping",
    "Going on long drives",
    "Ham radio",
    "Home / Interior decoration",
    "Learning new languages",
    "Listening to podcasts",
    "Mimicry",
    "Museums / Galleries / Exhibitions",
    "Numerology",
    "Painting / Sketching / Drawing",
    "Palmistry",
    "Pets",
    "Photography",
    "Playing cards",
    "Playing musical instruments",
    "Politics",
    "Scrabble",
    "Shopping",
    "Sightseeing",
    "Singing",
    "Social media",
    "Social service",
    "Solving Puzzles",
    "Stargazing",
    "Stitching",
    "Tailoring",
    "Technology",
    "Travel",
    "Tutoring",
    "Video / Computer Gaming",
    "Volunteer Work",
    "Wine tasting",
    "Writing"
];

export const musicGenres = [
    "Bhangra",
    "Bluegrass",
    "Blues",
    "Christian / Gospel",
    "Classical",
    "Classical - Carnatic",
    "Country",
    "Death metal",
    "Devotional",
    "Disco",
    "EDM (Electronic Dance Music)",
    "Film songs",
    "Folk music",
    "Fusion",
    "Ghazals",
    "Heavy metal",
    "Hip-Hop",
    "House music",
    "Indian / Hindustani",
    "Indie Rock",
    "Indipop",
    "Jazz",
    "K-pop",
    "Latin Music",
    "Melodies",
    "Opera",
    "Orchestra",
    "Pop",
    "Progressive metal",
    "Punk rock",
    "Qawalis",
    "Rap",
    "Reggae",
    "Remixes",
    "Rhythm & Blues",
    "Rock",
    "Sufi",
    "Techno",
    "Trance music",
    "Western"
];


export const readingInterests = [
    "Autobiographies / Biographies",
    "Business / Professional",
    "Classics",
    "Comics / Graphic novels",
    "Fantasy",
    "Fiction",
    "History",
    "Humor",
    "Literature",
    "Love reading almost anything",
    "Magazines / Newspapers",
    "Philosophy / Spiritual",
    "Poetry",
    "Romance",
    "Science fiction",
    "Self-help",
    "Short stories",
    "Thriller / Suspense",
    "Travelogues / Blogs"
];

export const movieGenres = [
    "Action",
    "Anime",
    "Classics",
    "Comedy",
    "Documentaries",
    "Drama",
    "Epics",
    "Fantasy",
    "Horror",
    "Movie fanatic",
    "Neo-noir",
    "Non-commercial / Art",
    "Romantic",
    "Romantic Comedies",
    "Sci-Fi",
    "Short films",
    "Thriller / Suspense",
    "World cinema"
];


export const sportsAndFitness = [
    "Aerobics",
    "American Football",
    "Archery",
    "Badminton",
    "Baseball",
    "Basketball",
    "Billiards / Snooker / Pool",
    "Bowling",
    "Boxing",
    "Cricket",
    "Cycling",
    "Football",
    "Golf",
    "Gym / Bodybuilding",
    "Handball",
    "Hockey",
    "Horseback Riding",
    "Jogging / Walking / Running",
    "Kabbadi",
    "Kho Kho",
    "Martial arts",
    "Motor Racing",
    "Pilates",
    "Polo",
    "Racquetball",
    "Rugby",
    "Sailing / Boating / Rowing",
    "Scuba Diving",
    "Shooting",
    "Skating / Snowboarding / Skiing",
    "Squash",
    "Swimming / Water sports",
    "Table tennis",
    "Tennis",
    "Throwball",
    "Volleyball",
    "Weight lifting",
    "Winter / Rink sports",
    "Wrestling (Phelwani) / Khusti",
    "Yoga / Meditation",
    "Zumba"
];

export const cuisines = [
    "American",
    "Arabic",
    "Bengali",
    "Brazilian",
    "Chinese",
    "Continental",
    "Ethiopian",
    "Fast food",
    "French",
    "Greek",
    "Gujarati",
    "Italian",
    "Japanese",
    "Konkan",
    "Korean",
    "Lebanese",
    "Malaysian",
    "Marathi",
    "Mediterranean",
    "Mexican",
    "Mughlai",
    "North Indian",
    "Odia",
    "Oriental",
    "Parsi",
    "Punjabi",
    "Rajasthani",
    "Soul Food",
    "South Indian",
    "Spanish",
    "Srilankan",
    "Thai",
    "Turkish",
    "Vietnamese"
];



export const languages = [
    "Afrikaans",
    "Angika",
    "Arabic",
    "Assamese",
    "Awadhi",
    "Bahasa",
    "Bengali",
    "Bhojpuri",
    "Bihari",
    "Burmese",
    "Cantonese",
    "Chhattisgarhi",
    "Croatian",
    "Danish",
    "Dogri",
    "Dutch",
    "English",
    "Finnish",
    "French",
    "Garhwali",
    "German",
    "Greek",
    "Gujarati",
    "Haryanvi",
    "Hebrew",
    "Himachali",
    "Hindi",
    "Italian",
    "Japanese",
    "Kannada",
    "Kashmiri",
    "Konkani",
    "Korean",
    "Kumaoni",
    "Kutchi",
    "Lambadi",
    "Maithili",
    "Malay",
    "Malayalam",
    "Malvani",
    "Mandarin",
    "Manipuri",
    "Marathi",
    "Marwadi",
    "Mizo",
    "Nepalese",
    "Norwegian",
    "Oriya",
    "Pahari",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Pushto",
    "Rajasthani",
    "Russian",
    "Sambalpuri",
    "Sanskrit",
    "Sindhi",
    "Sinhala",
    "Sourashtra",
    "Spanish",
    "Swahili",
    "Swedish",
    "Tagalog",
    "Tamil",
    "Telugu",
    "Thai",
    "Tulu",
    "Turkish",
    "Urdu",
    "Vietnamese"
];
